return {
	lsp              = true,
	treesitter       = true,
	neotree          = true,
	telescope        = true,
	gitsigns         = true,
	cmp              = true,
	blink            = true,
	which_key        = true,
	indent_blankline = true,
	notify           = true,
	flash            = true,
	trouble          = true,
	illuminate       = true,
	dashboard        = true,
	lazy             = true,
	mini             = true,
	snacks           = true,
	noice            = true,
	navic            = true,
}
