# ╔⦿════════════════════════════════════════════════════════════⦿╗
# ║   ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓   ║
# ║                                                              ║
# ║   ██╗  ██╗ █████╗ ██████╗ ██████╗ ██╗  ██╗ █████╗ ████████╗  ║
# ║   ██║  ██║██╔══██╗██╔══██╗██╔══██╗██║  ██║██╔══██╗╚══██╔══╝  ║
# ║   ███████║███████║██████╔╝██║  ██║███████║███████║   ██║     ║
# ║   ██╔══██║██╔══██║██╔══██╗██║  ██║██╔══██║██╔══██║   ██║     ║
# ║   ██║  ██║██║  ██║██║  ██║██████╔╝██║  ██║██║  ██║   ██║     ║
# ║   ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝     ║
# ║                                                              ║
# ║  ▌ INDUSTRIAL TERMINAL THEME                                 ║
# ║  ▌ tactical olive • balanced contrast                        ║
# ║                                                              ║
# ║  ──────────────────────────────────────────────────────────  ║
# ║   // mode   : M1                                             ║
# ║   // target : kitty                                          ║
# ║   // author : g-kirti                                        ║
# ║  ──────────────────────────────────────────────────────────  ║
# ║                                                              ║
# ╠⦿═════════════════════════[ CONFIG ]═════════════════════════⦿╣
# ║                                                              ║
# ╚⦿════════════════════════════════════════════════════════════⦿╝


#         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#                                UI
#         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

foreground                    #c4c7b1
background                    #262c1c

selection_foreground          #1a1d14
selection_background          #ccb521

cursor                        #c4c7b1
cursor_text_color             #262c1c

scrollbar_handle_color        #464d2e
scrollbar_track_color         #3a4529

url_color                     #3f90a9

active_border_color           #ccb521
inactive_border_color         #363b27
bell_border_color             #c2a259

macos_titlebar_color          system
wayland_titlebar_color        #262c1c

active_tab_background         #464d2e
active_tab_foreground         #c4c7b1

inactive_tab_background       #3a4529
inactive_tab_foreground       #89886f

tab_bar_background            #1b2115

mark1_foreground              #1a1d14
mark1_background              #3f90a9

mark2_foreground              #1a1d14
mark2_background              #ccb521

mark3_foreground              #1a1d14
mark3_background              #c8653e


#         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#                           ANSI Palette
#         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# black
color0                        #1a1d14
color8                        #707761

# red
color1                        #c8653e
color9                        #cc714d

# green                      
color2                        #52a830
color10                       #78c25a

# yellow
color3                        #ccb521
color11                       #e5d25c

# blue                    (tactical teal)
color4                        #2f9982
color12                       #6aaea0

  # magenta                   (camel)
color5                        #c2a259
color13                       #d0b77f

# cyan                       (UN blue)
color6                        #3f90a9
color14                       #79b4c6

# white                      
color7                        #acac9c
color15                       #c2c1b4

# Additional
color16                       #1b2115
